---
dist: trusty
sudo: false
language: php

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - DB_HOST=localhost
    - DB_USER=travis
    - DB_PASSWORD=DB_NAME=2moons
    - ADMIN_NAME=admin
    - ADMIN_PASSWORD=admin
    - ADMIN_MAIL=mail@example.com

php:
  - '7.0'

matrix:
  fast_finish: true

install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS 2moons;' -uroot
  - composer install

before_script:
  - phpenv config-rm xdebug.ini
  - '! find . ! -path "./includes/libs/*" ! -path "./vendor/*" -type f -name "*.php" -exec php -d error_reporting=32767 -l {} \; 2>&1 >&- | grep "^"'
  # Start a web server on port 8888, run in the background; wait for
  # initialization.
  - nohup php -S localhost:8888 > /dev/null 2>&1 &

script:
  - 'vendor/bin/phpunit'
# - phpdbg -qrr phpunit